# Generated by Django 4.2.5 on 2023-12-09 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0004_events_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events_comments',
            name='events',
        ),
    ]
