# Generated by Django 4.2.5 on 2023-12-09 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0005_remove_events_comments_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events_comments',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zohoapp.company_details'),
        ),
    ]
