# Generated by Django 4.2.5 on 2023-12-09 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0006_alter_events_comments_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='end',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='events',
            old_name='start',
            new_name='start_date',
        ),
    ]
