# Generated by Django 4.2.5 on 2023-12-11 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0009_remove_attendance_comments_alter_attendance_leave'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
